name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:

  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]


jobs:
  

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the image
        run:  docker build -t blockmay/fidle-frontend-desktop .

      - name: tag the image
        run:  docker tag blockmay/fidle-frontend-desktop blockmay/fidle-frontend-desktop:latest
      
      - name: push the image
        run:  docker push blockmay/fidle-frontend-desktop:latest